# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DriftWord
author: Jordan Shelswell
email: jordanshelswell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A place where oddities share their opinions about existing in our crazy world.
  News, science, and society are all on the table,
  sprinkeled with day to day exploration of new topics and skills.
  Come join us as we drift through this wonderfully worded world.
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://jordanshelswell.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ShelswellJordan
github_username:  jordanshelswell
linkedin_username: jordanshelswell

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-analytics

# Plugin Variables
jekyll_analytics:
  GoogleAnalytics:        # Add, if you want to track with Google Analytics
    id: UA-125898541-1         # Required - replace with your tracking id
    anonymizeIp: false    # Optional - Default: false - set to true for anonymized tracking

image: /path/to/your/default/image.png


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
